# Default initial positions for openarm's ros2_control fake system

initial_positions:
  openarm_finger_joint1: 0
  openarm_joint1: 0
  openarm_joint2: 0
  openarm_joint3: 0
  openarm_joint4: 0
  openarm_joint5: 0
  openarm_joint6: 0
  openarm_joint7: 0