# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - openarm_joint1
      - openarm_joint2
      - openarm_joint3
      - openarm_joint4
      - openarm_joint5
      - openarm_joint6
      - openarm_joint7
    action_ns: follow_joint_trajectory
    default: true