# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController



    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - openarm_joint1
      - openarm_joint2
      - openarm_joint3
      - openarm_joint4
      - openarm_joint5
      - openarm_joint6
      - openarm_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position